#pragma once

#define M_WALL  0
#define M_ROOF  1
#define M_FLOOR  2
#define M_NO_GATE_WALL  3
#define M_NO_GATE_ROOF  4
#define M_NO_GATE_FLOOR  5
#define M_PERFORATED_WALL  6
#define M_LASER_LAUNCH_PAD  7
#define M_LASER_CATHCER  8
#define M_EXIT  9
#define M_PILLAR  10
#define M_STAIRS  11
#define M_CATWALK  12
#define M_CATWALK_SHORT  13
#define M_CATWALK_FENCE  14
#define M_CATWALK_FENCE_SHORT  15
#define M_CATWALK_PILLAR  16
#define M_GATE_ORANGE  17
#define M_GATE_BLUE  18
#define M_PLAYER  19
#define M_GUN  20
#define M_HAND_OBJ  21
#define M_BUTTON  22
#define M_DOOR  23
#define M_DOOR_ARCH  24
#define M_TURRET  25
#define M_PISTON  26
#define M_GLASS  27
#define M_BULLET  28
#define M_BED  29
#define M_CHAIR  30
#define M_TORPEDO  31
#define PS_PIXEL  32
#define PS_GATE_POS  33
#define PS_NUM  34
#define PS_DISSOLVE  35
#define VS_VERTEX  36
#define VS_SKIN_MESH  37
#define I_LOGO  38
#define I_NUMBERS  39
#define I_DISSOLVE  40
#define I_FRAME  41
#define I_COMMON_FRAME  42
#define I_COMMON_SELECT_FRAME  43
#define I_RANK_S  44
#define I_RANK_A  45
#define I_RANK_B  46
#define I_RANK_C  47
#define I_RANK_SHADOW  48
#define I_PAD_A  49
#define I_PAD_B  50
#define I_PAD_X  51
#define I_PAD_Y  52
#define I_PAD_LT  53
#define I_PAD_RT  54
#define I_PAD_RB  55
#define I_PAD_CONTROLLER  56
#define I_LOADING  57
#define I_LOADING_FADE  58
#define I_LOADING_UNDER  59
#define I_RANKING_FRAME  60
#define I_RANKING_ARROW  61
#define I_RANKING_FIRST  62
#define I_RANKING_SECOND  63
#define I_RANKING_THIRD  64
#define I_RANKING_FORCE  65
#define I_RANKING_FIFTH  66
#define I_SAVE_ARM  67
#define I_SAVE_ARM_FRAME  68
#define I_SAVE_WINDOW  69
#define I_DECIDE_ARM  70
#define I_DECIDE_ARM_FRAME  71
#define I_DECIDE_WINDOW  72
#define I_SELECT_WINDOW_BACK  73
#define I_SELECT_WINDOW  74
#define I_NOT_RELEASE_FRAME  75
#define I_RELEASE_FRAME  76
#define I_STAGE_SELECT_FRAME  77
#define I_DECORATIVE_FRAME  78
#define I_DIVIDING_LINE  79
#define I_TIME_BACK  80
#define I_SELECT_OBI  81
#define I_STAGE_IMAGE_0  82
#define I_STAGE_IMAGE_1  83
#define I_STAGE_IMAGE_2  84
#define I_STAGE_IMAGE_3  85
#define I_STAGE_IMAGE_4  86
#define I_STAGE_IMAGE_5  87
#define I_STAGE_IMAGE_6  88
#define I_STAGE_IMAGE_7  89
#define I_STAGE_IMAGE_8  90
#define I_STAGE_IMAGE_9  91
#define I_TUTORIAL_FRAME  92
#define I_TUTORIAL_PERFECT  93
#define I_TUTORIAL_TEXT_0  94
#define I_TUTORIAL_TEXT_1  95
#define I_TUTORIAL_TEXT_2  96
#define I_TUTORIAL_TEXT_3  97
#define I_TUTORIAL_TEXT_4  98
#define I_TUTORIAL_TEXT_5  99
#define I_TUTORIAL_TEXT_6  100
#define I_TUTORIAL_TEXT_7  101
#define I_TUTORIAL_TEXT_8  102
#define I_EXPO_MOVE  103
#define I_EXPO_DASH  104
#define I_EXPO_JUMP  105
#define I_EXPO_GATE_0  106
#define I_EXPO_GATE_1  107
#define I_EXPO_GATE_2  108
#define I_NOW_HP_BAR  109
#define I_HIT_HP_BAR  110
#define I_BASE_HP_BAR  111
#define I_HP_FRAME  112
#define I_DAMAGE_FILLTER  113
#define I_TIME_BAR  114
#define I_LOOK_SITE  115
#define I_CREATE_GATE_ORANGE  116
#define I_CREATE_GATE_BLUE  117
#define I_NOT_CREATE_GATE_ORANGE  118
#define I_NOT_CREATE_GATE_BLUE  119
#define I_OPTION_WINDOW  120
#define I_BASE_BAR  121
#define I_MAIN_BAR  122
#define I_PLUS_BAR  123
#define I_CLEAR_WINDOW  124
#define I_CLEAR_TIME_FRAME  125
#define I_RANKING_UPDATE  126
#define I_VOLUME_POINT  127
#define I_TUTORIAL_TEST_1  128
#define I_TUTORIAL_TEST_2  129
#define I_TUTORIAL_TEST_3  130
#define S_LANDING  131
#define S_WALK  132
#define S_SHOT_PLAYER  133
#define S_DAMAGE  134
#define S_GATE_OPEN  135
#define S_WARP  136
#define S_BUTTON_PUSH  137
#define S_DOOR_OPEN  138
#define S_SHOT_ENERGY  139
#define S_CATCH_ENERGY  140
#define S_CANCEL  141
#define S_DECIDE  142
#define S_CURSOR_MOVE  143
#define B_TITLE  144
#define B_STAGE_SELECT  145
#define B_MAIN  146
#define B_RESULT  147
#define E_GATE_BULLET_BLUE  148
#define E_GATE_BULLET_ORANGE  149
#define E_DEATH_TURRET  150
#define E_BULLET  151
#define E_MUZZLE_FLASH  152
#define E_GATE_DELETE  153
#define E_LASER_BULLET  154
