#pragma once

#define M_WALL  0
#define M_ROOF  1
#define M_FLOOR  2
#define M_NO_GATE_WALL  3
#define M_NO_GATE_ROOF  4
#define M_NO_GATE_FLOOR  5
#define M_PERFORATED_WALL  6
#define M_LASER_LAUNCH_PAD  7
#define M_LASER_CATHCER  8
#define M_EXIT  9
#define M_PILLAR  10
#define M_STAIRS  11
#define M_CATWALK  12
#define M_CATWALK_SHORT  13
#define M_CATWALK_FENCE  14
#define M_CATWALK_FENCE_SHORT  15
#define M_CATWALK_PILLAR  16
#define M_GATE_ORANGE  17
#define M_GATE_BLUE  18
#define M_PLAYER  19
#define M_GUN  20
#define M_HAND_OBJ  21
#define M_BUTTON  22
#define M_DOOR  23
#define M_DOOR_ARCH  24
#define M_TURRET  25
#define M_PISTON  26
#define M_GLASS  27
#define M_BULLET  28
#define PS_PIXEL  29
#define PS_GATE_POS  30
#define PS_NUM  31
#define VS_VERTEX  32
#define VS_SKIN_MESH  33
#define I_NUMBERS  34
#define I_DISSOLVE  35
#define I_COMMON_FRAME  36
#define I_COMMON_SELECT_FRAME  37
#define I_RANK_S  38
#define I_RANK_A  39
#define I_RANK_B  40
#define I_RANK_C  41
#define I_RANK_SHADOW  42
#define I_PAD_A  43
#define I_PAD_B  44
#define I_PAD_X  45
#define I_PAD_Y  46
#define I_PAD_LT  47
#define I_PAD_RT  48
#define I_PAD_RB  49
#define I_LOADING  50
#define I_LOADING_FADE  51
#define I_LOADING_UNDER  52
#define I_RANKING_WINDOW  53
#define I_RANKING_ARROW  54
#define I_SAVE_ARM  55
#define I_SAVE_ARM_FRAME  56
#define I_SAVE_WINDOW  57
#define I_DECIDE_ARM  58
#define I_DECIDE_ARM_FRAME  59
#define I_DECIDE_WINDOW  60
#define I_SELECT_WINDOW_BACK  61
#define I_SELECT_WINDOW  62
#define I_NOT_RELEASE_FRAME  63
#define I_RELEASE_FRAME  64
#define I_STAGE_SELECT_FRAME  65
#define I_BEST_TIME_FRAME  66
#define I_DECORATIVE_FRAME  67
#define I_DIVIDING_LINE  68
#define I_TIME_BACK  69
#define I_SELECT_OBI  70
#define I_STAGE_IMAGE_0  71
#define I_STAGE_IMAGE_1  72
#define I_STAGE_IMAGE_2  73
#define I_STAGE_IMAGE_3  74
#define I_STAGE_IMAGE_4  75
#define I_STAGE_IMAGE_5  76
#define I_STAGE_IMAGE_6  77
#define I_STAGE_IMAGE_7  78
#define I_STAGE_IMAGE_8  79
#define I_STAGE_IMAGE_9  80
#define I_STAGE_IMAGE_10  81
#define I_STAGE_IMAGE_11  82
#define I_STAGE_IMAGE_12  83
#define I_STAGE_IMAGE_13  84
#define I_STAGE_IMAGE_14  85
#define I_NOW_HP_BAR  86
#define I_HIT_HP_BAR  87
#define I_BASE_HP_BAR  88
#define I_HP_FRAME  89
#define I_DAMAGE_FILLTER  90
#define I_TIME_BAR  91
#define I_LOOK_SITE  92
#define I_CREATE_GATE_ORANGE  93
#define I_CREATE_GATE_BLUE  94
#define I_NOT_CREATE_GATE_ORANGE  95
#define I_NOT_CREATE_GATE_BLUE  96
#define I_OPTION_WINDOW  97
#define I_BASE_SOUND_BAR  98
#define I_MAIN_SOUND_BAR  99
#define I_CLEAR_WINDOW  100
#define I_CLEAR_TIME_FRAME  101
#define I_RANKING_UPDATE  102
#define I_VOLUME_POINT  103
#define I_TUTORIAL_TEST_1  104
#define I_TUTORIAL_TEST_2  105
#define I_TUTORIAL_TEST_3  106
#define S_LANDING  107
#define S_WALK  108
#define S_SHOT_PLAYER  109
#define S_DAMAGE  110
#define S_GATE_OPEN  111
#define S_WARP  112
#define S_BUTTON_PUSH  113
#define S_DOOR_OPEN  114
#define S_SHOT_ENERGY  115
#define S_CATCH_ENERGY  116
#define S_CANCEL  117
#define S_DECIDE  118
#define S_CURSOR_MOVE  119
#define B_TITLE  120
#define B_STAGE_SELECT  121
#define B_MAIN  122
#define B_RESULT  123
#define E_GATE_BULLET_BLUE  124
#define E_GATE_BULLET_ORANGE  125
#define E_DEATH_TURRET  126
#define E_BULLET  127
#define E_MUZZLE_FLASH  128
#define E_GATE_DELETE  129
#define E_LASER_BULLET  130
